const prefixMap = {
  'background-color': 'bg',
  'box-shadow': 'shadow',
  'flex-basis': 'basis',
  'font-size': 'text',
  'grid-template-columns': 'grid-cols',
  'grid-template-rows': 'grid-rows',
  'letter-spacing': 'tracking',
  'line-height': 'leading',
  'margin-bottom': 'mb',
  'margin-left': 'ml',
  'margin-right': 'mr',
  'margin-top': 'mt',
  'max-height': 'max-h',
  'max-width': 'max-w',
  'min-height': 'min-h',
  'min-width': 'min-w',
  'padding-bottom': 'pb',
  'padding-left': 'pl',
  'padding-right': 'pr',
  'padding-top': 'pt',
  'z-index': 'z',
  bottom: 'bottom',
  color: 'text',
  fill: 'fill',
  flex: 'flex',
  gap: 'gap',
  height: 'h',
  left: 'left',
  margin: 'm',
  opacity: 'opacity',
  padding: 'p',
  right: 'right',
  stroke: 'stroke',
  top: 'top',
  transform: 'transform',
  width: 'w',
};

module.exports = prefixMap;
