const prefixMap = {
  'min-height': 'min-h',
  'min-width': 'min-w',
  'max-height': 'max-h',
  'max-width': 'max-w',
  width: 'w',
  height: 'h',
  transition: 'transition',
  'z-index': 'z',
  transform: 'transform',
  'letter-spacing': 'tracking',
  'line-height': 'leading',
  'font-size': 'text',
  top: 'top',
  left: 'left',
  right: 'right',
  bottom: 'bottom',
  gap: 'gap',
  stroke: 'stroke',
  fill: 'fill',
  'grid-template-columns': 'grid-cols',
  'grid-template-rows': 'grid-rows',
  flex: 'flex',
  'box-shadow': 'shadow',
  'flex-basis': 'basis',
};

module.exports = prefixMap;
