const pseudoVariantMappings = {
  'file-selector-button': 'file',
  'first-child': 'first',
  'first-letter': 'first-letter',
  'first-line': 'first-line',
  'first-of-type': 'first-of-type',
  'focus-visible': 'focus-visible',
  'focus-within': 'focus-within',
  'in-range': 'in-range',
  'last-child': 'last',
  'last-of-type': 'last-of-type',
  'nth-child(even)': 'even',
  'nth-child(odd)': 'odd',
  'only-child': 'only',
  'only-of-type': 'only-of-type',
  'out-of-range': 'out-of-range',
  'placeholder-shown': 'placeholder-shown',
  'read-only': 'read-only',
  active: 'active',
  after: 'after',
  autofill: 'autofill',
  backdrop: 'backdrop',
  before: 'before',
  checked: 'checked',
  default: 'default',
  disabled: 'disabled',
  empty: 'empty',
  enabled: 'enabled',
  focus: 'focus',
  hover: 'hover',
  indeterminate: 'indeterminate',
  invalid: 'invalid',
  marker: 'marker',
  placeholder: 'placeholder',
  required: 'required',
  selection: 'selection',
  target: 'target',
  valid: 'valid',
  visited: 'visited',
};

module.exports = pseudoVariantMappings;
